workflows:
  android-workflow:
    name: HashtagStation Android APK
    max_build_duration: 60
    environment:
      flutter: 3.19.6
      java: 17
    scripts:
      - name: Set Flutter SDK path
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release --no-obfuscate
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - sawwwaisingh@gmail.com
        notify:
          success: true
          failure: true